name: Auto-Lint

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - develop

jobs:
  lint:
    if: contains(github.event.head_commit.message, 'skip ci') == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install Dependencies
        run: yarn install
      - name: Lint Write
        run: npx prettier --write ./contracts
      - name: Lint Check
        run: npx prettier --check ./contracts